### ISSUE TITLE
Change default key combination

### ISSUE THREAD

**Issue by JonasJurczok** [Tarrke/factorio-clock#9]
Hey,
I just saw that shift+c is the default key for interacting the chronometer.
shift+c is also used by even distribution to get rid of trash items. Maybe you want to change the default key to not interfere with this add-on?

**Comment by Tarrke** [comment]
Changed to ALT+C as I don't have any creativity. Any comment on that is welcome.

**Comment by JonasJurczok** [comment]
Just a hint: if you include "closes #9" in your commit message GitHub will close the issue for you and reference the commit/pr :)
